"""add_image_gen_daily_usage

Revision ID: a1b2c3d4e5f6
Revises: d327932d860e
Create Date: 2025-12-16 14:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1b2c3d4e5f6"
down_revision: Union[str, None] = "d327932d860e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    insp = sa.inspect(bind)

    table_name = "image_gen_daily_usage"
    if insp.has_table(table_name):
        return
    op.create_table(
        "image_gen_daily_usage",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("usage_date", sa.String(length=10), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(op.f("ix_image_gen_daily_usage_user_id"), "image_gen_daily_usage", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_image_gen_daily_usage_user_id"), table_name="image_gen_daily_usage")
    op.drop_table("image_gen_daily_usage")
    # ### end Alembic commands ###
